# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2622e99d5239ae7c1c98810c7aeb144537de572bab2ef753933ca9e7e408325aae4381314361f3b94ff3ba3eff4adf4b2a886ee209c04175fe9570ba4a7d51ed

test:
  secret_key_base: c4e49437e7306fadfe3fb779f795da0f28de37143d61032593766ca4755af5bc1d502ccf221ee970471af33a816b2a4d79f9466d83d271cc1ed21f8f4c8c84f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
